name: Ensure Tests for Java Code

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - '**/*.java'
  pull_request_review:
    types: [submitted]
    paths:
      - '**/*.java'

jobs:
  check-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or the version of JDK your project uses
        distribution: 'adopt' # Use 'adopt', 'zulu', 'temurin', etc. depending on your preference

    - name: Check for 'no-tests-needed' label
      id: check_label
      run: |
        echo "has_label=false" >> $GITHUB_ENV
        for label in "${{ github.event.pull_request.labels[*].name }}"; do
          if [[ "$label" == "no-tests-needed" ]]; then
            echo "has_label=true" >> $GITHUB_ENV
            break
          fi
        done

    - name: Check for test files and justification
      id: check_tests_justification
      run: |
        if [ "${{ env.has_label }}" != "true" ]; then
          # List all changed Java files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '*.java')
          
          # Check for corresponding test files
          MISSING_TESTS=false
          MISSING_FILES=""
          for FILE in $CHANGED_FILES; do
            if [[ $FILE != *'/test/'* && $FILE != *'/tests/'* ]]; then
              TEST_FILE=$(echo $FILE | sed 's/src/test/g')
              if ! git diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- "$TEST_FILE"; then
                echo "Missing test file for $FILE"
                MISSING_TESTS=true
                MISSING_FILES="$MISSING_FILES\n$FILE"
              fi
            fi
          done

          if [ "$MISSING_TESTS" = true ]; then
            echo "missing_tests=true" >> $GITHUB_ENV
            echo "missing_files=$MISSING_FILES" >> $GITHUB_ENV

            # Fetch comments to check for justification
            COMMENTS=$(gh pr view ${{ github.event.pull_request.number }} --comments)
            JUSTIFICATION_FOUND=false
            for COMMENT in $COMMENTS; do
              if [[ $COMMENT == Tests\ not\ required:* ]]; then
                JUSTIFICATION_FOUND=true
                break
              fi
            done

            if [ "$JUSTIFICATION_FOUND" = true ]; then
              echo "justification=provided" >> $GITHUB_ENV
            else
              echo "justification=not found" >> $GITHUB_ENV
            fi
          else
            echo "missing_tests=false" >> $GITHUB_ENV
          fi
        else
          echo "missing_tests=false" >> $GITHUB_ENV
        fi

    - name: Add PR comment if tests are missing and no justification
      if: env.missing_tests == 'true' && env.justification == 'not found'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `The following Java files are missing corresponding test files:${{ env.missing_files }}. If these files are not testable, please provide a justification in the following format: "Tests not required: <justification>". Justification not found.`
          })
